/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.p1c2.fronted;

import com.mycompany.p1c2.fronted.funciones.*;
import java.awt.BorderLayout;

/**
 *
 * @author sergi
 */
public class VisualPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VisualPrincipal
     */
    public VisualPrincipal() {
        initComponents();
        verReproductor();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPMain = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuCrearPista = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jmenuEliminarPista = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuReproductorInicio = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 700));

        javax.swing.GroupLayout JPMainLayout = new javax.swing.GroupLayout(JPMain);
        JPMain.setLayout(JPMainLayout);
        JPMainLayout.setHorizontalGroup(
            JPMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 695, Short.MAX_VALUE)
        );
        JPMainLayout.setVerticalGroup(
            JPMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 491, Short.MAX_VALUE)
        );

        jMenu1.setText("Archivo");

        menuCrearPista.setText("Crear Pista");
        menuCrearPista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCrearPistaActionPerformed(evt);
            }
        });
        jMenu1.add(menuCrearPista);

        jMenuItem2.setText("Modificar Pista");
        jMenu1.add(jMenuItem2);

        jmenuEliminarPista.setText("Eliminar Pista");
        jmenuEliminarPista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuEliminarPistaActionPerformed(evt);
            }
        });
        jMenu1.add(jmenuEliminarPista);

        jMenuItem4.setText("Servir Pista");
        jMenu1.add(jMenuItem4);

        jMenuItem5.setText("Guardar Pista");
        jMenu1.add(jMenuItem5);

        jMenuItem6.setText("Recuperar Pista");
        jMenu1.add(jMenuItem6);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Reproductor");

        menuReproductorInicio.setText("Inicio");
        menuReproductorInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuReproductorInicioActionPerformed(evt);
            }
        });
        jMenu2.add(menuReproductorInicio);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmenuEliminarPistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuEliminarPistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmenuEliminarPistaActionPerformed

    private void menuCrearPistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCrearPistaActionPerformed
        // TODO add your handling code here:
        CrearPista crearPista = new CrearPista();
        crearPista.setSize(this.getWidth()-9, this.getHeight()-52);
        crearPista.setLocation(0, 0);
        JPMain.removeAll();
        JPMain.add(crearPista,BorderLayout.CENTER);
        JPMain.revalidate();
        JPMain.repaint();
        
    }//GEN-LAST:event_menuCrearPistaActionPerformed

    private void menuReproductorInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuReproductorInicioActionPerformed
        // TODO add your handling code here:
        verReproductor();
    }//GEN-LAST:event_menuReproductorInicioActionPerformed

      private void verReproductor(){
            Reproductor reproductor = new Reproductor();
            reproductor.setSize(this.getWidth()-9, this.getHeight()-52);
            reproductor.setLocation(0, 0);
            JPMain.removeAll();
            JPMain.add(reproductor,BorderLayout.CENTER);
            JPMain.revalidate();
            JPMain.repaint();
      }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPMain;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jmenuEliminarPista;
    private javax.swing.JMenuItem menuCrearPista;
    private javax.swing.JMenuItem menuReproductorInicio;
    // End of variables declaration//GEN-END:variables
}
