
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.mycompany.p1c2.ReglasGram.pistas;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ID_BOOLEAN = 27;
  public static final int CASO = 10;
  public static final int MULT = 62;
  public static final int CHAR = 35;
  public static final int STRING_SIMPLE = 34;
  public static final int IGUALACION = 46;
  public static final int MENSAJE = 23;
  public static final int ORDENAR = 20;
  public static final int ENTERO = 32;
  public static final int SI = 7;
  public static final int XOR = 60;
  public static final int DIFERENTE = 51;
  public static final int MAYQ = 49;
  public static final int SEMI = 43;
  public static final int ID_VARIABLE = 36;
  public static final int ID_CADENA = 30;
  public static final int INVALID = 70;
  public static final int PRINCIPAL = 24;
  public static final int NOT = 61;
  public static final int AND = 56;
  public static final int MENQ = 48;
  public static final int IGUAL = 42;
  public static final int NOR = 59;
  public static final int NAND = 57;
  public static final int SINO = 8;
  public static final int OR = 58;
  public static final int TAB = 45;
  public static final int MIENTRAS = 14;
  public static final int EXTIENDE = 3;
  public static final int PISTA = 2;
  public static final int DIV = 65;
  public static final int INCREMENTO = 54;
  public static final int CONTINUAR = 16;
  public static final int LLAI = 68;
  public static final int SUMA = 63;
  public static final int MAS_IGUAL = 53;
  public static final int KEEP = 4;
  public static final int LLAD = 69;
  public static final int SALIR = 11;
  public static final int EOF = 0;
  public static final int BOOLEAN = 25;
  public static final int DECIMAL = 31;
  public static final int ARREGLO = 6;
  public static final int REPRODUCIR = 18;
  public static final int MAY_QUE = 50;
  public static final int DECREMENTO = 55;
  public static final int error = 1;
  public static final int NULO = 52;
  public static final int COMA = 41;
  public static final int ID_DOBLE = 28;
  public static final int MODULO = 66;
  public static final int MENOS = 64;
  public static final int MEN_QUE = 47;
  public static final int RETORNA = 17;
  public static final int SWITCH = 9;
  public static final int POTENCIA = 67;
  public static final int PAI = 37;
  public static final int LONGITUD = 22;
  public static final int SUMARIZAR = 21;
  public static final int DEFAULT = 12;
  public static final int PAD = 38;
  public static final int ID_ENTERO = 26;
  public static final int ID_CARACTER = 29;
  public static final int CORI = 39;
  public static final int HACER = 15;
  public static final int ESPERAR = 19;
  public static final int STRING = 33;
  public static final int PARA = 13;
  public static final int CORD = 40;
  public static final int SALTO = 44;
  public static final int VAR = 5;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PISTA",
  "EXTIENDE",
  "KEEP",
  "VAR",
  "ARREGLO",
  "SI",
  "SINO",
  "SWITCH",
  "CASO",
  "SALIR",
  "DEFAULT",
  "PARA",
  "MIENTRAS",
  "HACER",
  "CONTINUAR",
  "RETORNA",
  "REPRODUCIR",
  "ESPERAR",
  "ORDENAR",
  "SUMARIZAR",
  "LONGITUD",
  "MENSAJE",
  "PRINCIPAL",
  "BOOLEAN",
  "ID_ENTERO",
  "ID_BOOLEAN",
  "ID_DOBLE",
  "ID_CARACTER",
  "ID_CADENA",
  "DECIMAL",
  "ENTERO",
  "STRING",
  "STRING_SIMPLE",
  "CHAR",
  "ID_VARIABLE",
  "PAI",
  "PAD",
  "CORI",
  "CORD",
  "COMA",
  "IGUAL",
  "SEMI",
  "SALTO",
  "TAB",
  "IGUALACION",
  "MEN_QUE",
  "MENQ",
  "MAYQ",
  "MAY_QUE",
  "DIFERENTE",
  "NULO",
  "MAS_IGUAL",
  "INCREMENTO",
  "DECREMENTO",
  "AND",
  "NAND",
  "OR",
  "NOR",
  "XOR",
  "NOT",
  "MULT",
  "SUMA",
  "MENOS",
  "DIV",
  "MODULO",
  "POTENCIA",
  "LLAI",
  "LLAD",
  "INVALID"
  };
}

